-- ResumeFlow MySQL 建表脚本（与实体类完全一致，共 15 张表）
-- 说明：正常部署无需手动执行（ddl-auto: update 会自动建表）；仅在手动建表时使用

CREATE DATABASE IF NOT EXISTS resume_flow DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE resume_flow;

create table answer_material (deleted bit not null, enabled bit not null, sort_order integer, create_time datetime(6) not null, id bigint not null auto_increment, template_id bigint, update_time datetime(6) not null, user_id bigint not null, word_limit_type varchar(30), materialType varchar(50), short_name varchar(50), title varchar(100), content TEXT, primary key (id)) engine=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table application_template (deleted bit not null, is_default bit, create_time datetime(6) not null, id bigint not null auto_increment, update_time datetime(6) not null, user_id bigint not null, audience_type varchar(30), category varchar(100), name varchar(100), description varchar(500), skill_order varchar(512), ai_collaboration TEXT, career_plan TEXT, internship_description TEXT, project_description TEXT, self_evaluation TEXT, skill_keywords TEXT, primary key (id)) engine=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table autofill_log (deleted bit not null, filled_count integer, matched_count integer, sensitive_count integer, skipped_count integer, total_fields integer, create_time datetime(6) not null, id bigint not null auto_increment, template_id bigint, update_time datetime(6) not null, user_id bigint not null, fill_type varchar(20), status varchar(20), client_ip varchar(50), page_title varchar(500), page_url varchar(500), detail_json TEXT, primary key (id)) engine=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table award_certificate (deleted bit not null, sort_order integer, create_time datetime(6) not null, id bigint not null auto_increment, update_time datetime(6) not null, user_id bigint not null, award_year varchar(20), award_type varchar(50), award_name varchar(200), description varchar(500), primary key (id)) engine=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table content_variant (deleted bit not null, enabled bit not null, create_time datetime(6) not null, id bigint not null auto_increment, source_id bigint not null, update_time datetime(6) not null, user_id bigint not null, audience_type varchar(20) not null, job_direction varchar(20), length_type varchar(20) not null, source_type varchar(20) not null, field_type varchar(40), content TEXT, primary key (id)) engine=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table education_experience (deleted bit not null, is_default bit, sort_order integer, create_time datetime(6) not null, id bigint not null auto_increment, update_time datetime(6) not null, user_id bigint not null, end_date varchar(20), gpa varchar(20), start_date varchar(20), grade_rank varchar(30), advisor varchar(50), degree varchar(50), college varchar(100), major varchar(100), school varchar(100), school_tags varchar(100), lab varchar(200), research_direction varchar(300), thesis varchar(300), honors varchar(500), description TEXT, primary key (id)) engine=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table internship_experience (deleted bit not null, is_default bit, sort_order integer, create_time datetime(6) not null, id bigint not null auto_increment, update_time datetime(6) not null, user_id bigint not null, end_date varchar(20), start_date varchar(20), short_name varchar(50), audience_exclude varchar(100), company varchar(100), department varchar(100), position varchar(100), tech_stack varchar(500), description TEXT, highlights TEXT, template_priority varchar(255), primary key (id)) engine=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table profile_sync_state (deleted bit not null, create_time datetime(6) not null, id bigint not null auto_increment, profile_version bigint not null, update_time datetime(6) not null, user_id bigint not null, data_hash varchar(64), primary key (id)) engine=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table project_experience (deleted bit not null, is_default bit, sort_order integer, create_time datetime(6) not null, id bigint not null auto_increment, update_time datetime(6) not null, user_id bigint not null, end_date varchar(20), start_date varchar(20), short_name varchar(50), audience_exclude varchar(100), role varchar(100), projectName varchar(200), tech_stack varchar(500), description TEXT, project_intro TEXT, responsibilities TEXT, result TEXT, primary key (id)) engine=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table skill_profile (deleted bit not null, sort_order integer, create_time datetime(6) not null, id bigint not null auto_increment, update_time datetime(6) not null, user_id bigint not null, category varchar(50), level varchar(50), skill_key varchar(50), skillName varchar(100), content TEXT, primary key (id)) engine=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table sys_user (deleted bit not null, create_time datetime(6) not null, id bigint not null auto_increment, update_time datetime(6) not null, phone varchar(20), username varchar(50) not null, email varchar(100), password varchar(100) not null, primary key (id)) engine=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table template_experience_config (auto_fill_enabled bit not null, auto_fill_priority integer, deleted bit not null, display_order integer, included_in_resume bit not null, manual_selectable bit not null, create_time datetime(6) not null, id bigint not null auto_increment, source_id bigint not null, template_id bigint not null, update_time datetime(6) not null, user_id bigint not null, source_type varchar(20) not null, emphasis_tags varchar(512), primary key (id)) engine=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table user_custom_field (auto_fill_enabled boolean default true not null, deleted bit not null, enabled bit not null, manual_fill_enabled boolean default true not null, sensitive bit not null, sort_order integer, create_time datetime(6) not null, id bigint not null auto_increment, template_id bigint, update_time datetime(6) not null, user_id bigint not null, version bigint default 0 not null, field_type varchar(30) not null, length_type varchar(30), field_category varchar(50), source_ref varchar(50), field_key varchar(100) not null, field_name varchar(100) not null, template_ids varchar(200), field_value TEXT, match_keywords TEXT, primary key (id)) engine=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table user_preference (deleted bit not null, create_time datetime(6) not null, id bigint not null auto_increment, update_time datetime(6) not null, user_id bigint not null, content TEXT, primary key (id)) engine=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
create table user_profile (deleted bit not null, create_time datetime(6) not null, id bigint not null auto_increment, update_time datetime(6) not null, user_id bigint not null, accept_other_city varchar(10), gender varchar(10), graduation_date varchar(20), phone varchar(20), emergency_phone varchar(30), id_card varchar(30), qq varchar(30), reference_phone varchar(30), applicant_type varchar(50), bank_card varchar(50), degree varchar(50), emergency_contact varchar(50), expected_city varchar(50), name varchar(50), political_status varchar(50), target_city varchar(50), wechat varchar(50), current_location varchar(100), email varchar(100), expected_position varchar(100), major varchar(100), school varchar(100), target_position varchar(100), family_members varchar(500), self_introduction TEXT, primary key (id)) engine=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
alter table sys_user add constraint UK_51bvuyvihefoh4kp5syh2jpi4 unique (username);
